#cloud-config
# vim: syntax=yaml
#
# ***********************
# 	---- for more examples look at: ------
# ---> https://cloudinit.readthedocs.io/en/latest/topics/examples.html
# ******************************
#
ssh_authorized_keys:
  - ${ssh_key}
package_update: true
packages:
  - apt-transport-https
  - curl
  - gnupg2
  - net-tools
  - nfs-common
  - python3-pip
  - qemu-guest-agent
  - sysstat
  - unzip
  - oidc-agent-cli
  - qemu-guest-agent
runcmd:
  - [ systemctl, enable, qemu-guest-agent ]
  - [ systemctl, start, qemu-guest-agent ]
  - [ apt-get, autoclean ]
